### ISSUE TITLE
outputs.conf is missing when installing a dedicated search head

### ISSUE THREAD

**Issue by tomkregenbild** [BestBuy/splunk_cookbook#40]
the outputs.conf file is expected to be under templates/default/server but there is no such file.

Under templates/default there is an outputs.conf file but it is expecting different parameters than the ones passed when running the server recipe.

**Comment by emiller42** [comment]
Lack of testing coverage let this one through.  I should be able to get a fix in pretty quick, but 0.2.0 should be fully functional in the meantime.

**Comment by tomkregenbild** [comment]
@emiller42 Thanks, in addition the server dynamic config files are mentioned in the documentation but there is no code that deploys them to the server.

This will tell the splunk server to use the dynamic config files located in `templates/default/server/SERVER_CONFIG_FOLDER`:

```ruby
override_attributes(
  "splunk" => {
    "server_config_folder" => "prod"
  }
)
```

**Comment by emiller42** [comment]
Regarding `server_config_folder`:  One of the things I intend to eliminate is the need to modify the cookbook for normal use.  This means some things are going to get pushed into attributes where appropriate, and some other things are going to be left up to the user to manage.  

The idea of defining environments in this cookbook, and forcing users to put environment configs in this cookbook which then need to be excluded from source control, is going away.  This is a part of that. Now, it's not fully pulled out, so I'm making sure the remaining template (props.conf) is still handled.  But this is behavior that is going to be changing in the future.  We don't want to dictate how/where you define your environment specific configs.  

I've got working fixes for these locally, but I'm still working on proper testing.  (mocking nodes/roles in test kitchen)

**Comment by emiller42** [comment]
@tomkregenbild: If you can, please review the pull request and let me know if you run into any issues.  All test suites pass for me.

**Comment by tomkregenbild** [comment]
I started checking it on a fresh server and ran into this problem 

ERROR: Undefined node attribute or method `<<' on `node'. To set an attribute, use `<<=value' instead.

This error is generated on this line:
node.normal['splunk']['static_server_configs'] << "distsearch"

in the /var/chef/cache/cookbooks/splunk/recipes/server.rb cookbook.

I worked around by adding the foolowing line at the beginning of the recipe:
node.normal['splunk']['static_server_configs'] = ["web","transforms","limits","indexes"]
node.normal['splunk']['dynamic_server_configs'] = ["inputs","props"]


This error is happening because for some reason the array is not defined even though you have values  in the default template.

**Comment by tomkregenbild** [comment]
@emiller42 seems to work for me now.
