### ISSUE TITLE
authentication password should not be plain text

### ISSUE THREAD

**Issue by tomkregenbild** [BestBuy/splunk_cookbook#42]
I think it should be implemented using an encrypted password or an encrypted data bag.

**Comment by emiller42** [comment]
As long as you populate the `node['splunk']['auth']` attribute at a node.default level, it doesn't persist in the node on chef server.  So you can actually store the credentials however you like (Chef Vault, encrypted databag, something else) and populate it at runtime, minimizing exposure to the active chef run.

**Comment by tomkregenbild** [comment]
sounds good, thanks
